fpc1020-objs := fpc1020_main.o fpc1020_common.o fpc1020_capture.o fpc1020_regulator.o fpc1020_nav.o fpc1020_navlib.o
ccflags-y += -DVENDOR_EDIT
obj-$(CONFIG_FINGERPRINT_FPC_FPC1020_FAMILY)  += fpc1020.o
